from pathlib import Path

families = {
"Estrategia y narrativa": [
"Definir una promesa de experiencia reconocible en los primeros segundos.","Alinear el tono con la identidad NOIACORE.","Mantener el contenido original como fuente de verdad.","Evitar claims no verificables.","Usar la metáfora de protocolo como hilo conductor.","Ordenar la revelación desde vacío hacia señal.","Distinguir perfil, trabajo, stack y contacto.","Hacer que cada sección responda a una pregunta del visitante.","Conservar una narrativa serena y no comercial.","Usar el silencio como parte de la composición.","Evitar adornos que no aporten significado.","Hacer explícita la disponibilidad sin presión.","Dar a los expedientes una función demostrativa.","Conectar el hero con el sistema de proyectos.","Cerrar la experiencia con una llamada de contacto clara.","Mantener consistencia semántica entre español y metadata técnica.","No convertir la experiencia en una demo vacía.","Priorizar evidencia sobre autoelogio.","Hacer visible la procedencia de los proyectos.","Separar investigación pública de datos sensibles.","Usar el estado operativo como lenguaje de marca.","Mantener una dirección editorial estable.","Evitar contradicciones entre tono y comportamiento.","Permitir que la navegación se entienda sin explicación externa.","Validar que la atmósfera no eclipse el propósito."],
"Composición y jerarquía": [
"Establecer un foco primario inequívoco.","Usar asimetría controlada sin perder equilibrio.","Crear una escala de tamaños coherente.","Reservar el mayor contraste para el mensaje principal.","Usar reglas finas para estructurar el espacio.","Mantener un margen seguro en todos los viewport.","Evitar acumulación de elementos en el primer plano.","Dar respiración suficiente a cada sección.","Alinear bloques por ejes reconocibles.","Usar el vacío para separar conceptos.","Limitar la cantidad de focos luminosos simultáneos.","Mantener continuidad entre hero y ticker.","Construir un ritmo vertical deliberado.","Evitar que las cards parezcan un dashboard genérico.","Usar la imagen como evidencia y no como decoración.","Garantizar que los encabezados sobrevivan al responsive.","Mantener la línea central como elemento de orientación.","Controlar la profundidad de capas z-index.","Evitar cortes visuales accidentales.","Hacer que el footer cierre la composición.","Conservar un patrón de alineación en metadatos.","No superar una densidad informativa tolerable.","Proteger los controles flotantes del contenido.","Comprobar la lectura a 1280, 768 y 375 píxeles.","Validar el recorrido ocular con una captura limpia."],
"Tipografía y contenido": [
"Usar una sans geométrica legible para titulares.","Usar una mono solo para metadata operativa.","Reservar pesos finos para el protocolo.","Mantener contraste de tamaño entre título y cuerpo.","Controlar tracking en mayúsculas.","Evitar líneas de lectura excesivamente largas.","Garantizar interlineado cómodo en móvil.","No alterar textos existentes sin autorización.","Evitar traducciones automáticas que deformen claims.","Mantener nombres propios sin localización accidental.","Usar microcopy operativo en botones.","Distinguir enlaces de texto de etiquetas.","Conservar el idioma declarado en HTML.","Dar alt text útil a imágenes informativas.","Usar alt vacío en imágenes puramente decorativas.","Evitar texto incrustado en imágenes.","Mantener consistencia de capitalización.","Evitar jerga sin contexto en la narrativa.","Revisar signos, acentos y espacios.","No presentar métricas subjetivas como hechos.","Mantener el tono preciso y sereno.","Verificar truncamiento de textos largos.","Probar zoom de texto al 200%.","Usar estados de carga comprensibles.","Asegurar que el mensaje de protocolo sea seleccionable."],
"Color y materiales": [
"Usar negro absoluto como base.","Limitar la paleta a azules profundos y blancos fríos.","Eliminar tonos cálidos no intencionados.","Mantener contraste mínimo para texto normal.","No depender solo del color para estados.","Usar el azul frío como señal, no como relleno dominante.","Controlar la opacidad de bordes.","Evitar gradientes saturados.","Usar reflejos como material de agua negra.","Mantener consistencia entre imágenes y UI.","Evitar glow excesivo.","Separar fondo, superficie y foco con luminancia.","Proteger el texto sobre fotografías.","Controlar filtros de saturación.","Mantener sombras suaves y profundas.","Evitar blanco puro en grandes superficies.","Usar un único color de acción.","Validar contraste en hover y focus.","Comprobar la paleta con daltonismo simulado.","Mantener líneas visibles en pantallas OLED.","No usar ruido que degrade legibilidad.","Limitar partículas a puntos de baja densidad.","Usar el navy como transición, no como bloque plano.","Validar modo reducido sin pérdida de contraste.","Documentar tokens para impedir regresiones."],
"Movimiento e interacción": [
"Hacer lenta la entrada del protocolo.","Mostrar una línea que nazca desde el centro.","Afinar visualmente los extremos de la línea.","Decodificar letras antes de fijar el mensaje.","Mantener pausas entre protocolo y bienvenida.","Revelar la interfaz después de la bienvenida.","Evitar rebotes o easing infantil.","Usar transform y opacity para animar.","Mantener la interacción dentro de tiempos razonables.","Dar feedback visible al hover.","Dar feedback visible al focus.","Mantener la terminal accesible durante la navegación.","Evitar que un loop distraiga del contenido.","Usar movimiento ambiental de baja amplitud.","Mantener órbitas lentas y no protagonistas.","Usar partículas escasas.","Hacer que el cursor no sea obligatorio.","Permitir omitir la secuencia.","Respetar prefers-reduced-motion.","Evitar animaciones que bloqueen lectura.","No animar layout con cambios bruscos.","Evitar parallax pesado en móvil.","Mantener transiciones reversibles.","Comprobar que la carga no parezca un error.","Usar la misma lógica de señal en toda la página."],
"Accesibilidad y usabilidad": [
"Usar landmarks semánticos.","Mantener un único h1.","Ordenar headings sin saltos injustificados.","Garantizar navegación por teclado.","Mostrar focus visible.","Dar nombres accesibles a botones.","Proporcionar etiqueta al selector de idioma.","Mantener enlaces externos identificables.","No depender de hover para acciones esenciales.","Permitir cerrar el menú móvil con teclado.","Evitar captura permanente del foco.","Mantener contraste en estados deshabilitados.","Usar aria-live solo para cambios relevantes.","No anunciar cada frame de la decodificación.","Dar alternativa al preloader.","Mantener skip o salida del protocolo.","Probar con lector de pantalla.","Probar navegación sin ratón.","Probar zoom y reflow.","Evitar texto demasiado pequeño.","No usar iconos sin etiqueta.","Mantener targets táctiles cómodos.","Evitar scroll horizontal.","Proteger contenido ante reducción de movimiento.","Documentar limitaciones de conformidad."],
"Rendimiento y resiliencia": [
"Mantener el build sin errores.","Mantener TypeScript sin errores.","Servir imágenes desde almacenamiento compatible.","Usar dimensiones explícitas para imágenes.","Evitar assets locales grandes en public.","Limitar JavaScript no esencial.","Evitar loops que consuman CPU innecesariamente.","Usar CSS para movimiento ambiental.","Evitar layout shift en el hero.","Probar carga en móvil.","Mantener la primera vista utilizable.","Comprobar errores de consola.","Comprobar solicitudes fallidas.","Dar fallback si una imagen no carga.","No depender de un API externo para el contenido base.","Mantener enlaces externos con rel seguro.","Proteger el preloader de estados colgados.","Permitir omitir animación larga.","Evitar timers sin cleanup.","Limpiar intervalos al desmontar.","Mantener compatibilidad con navegadores modernos.","Verificar responsive en breakpoints críticos.","Comprobar el peso de fuentes.","Evitar dependencias innecesarias.","Guardar una versión reproducible."],
"Arquitectura visual y sistema": [
"Centralizar tokens de color.","Centralizar tiempos de animación.","Separar componentes por responsabilidad.","Mantener la página como composición modular.","Evitar estilos inline repetidos.","Documentar decisiones visuales.","Mantener una convención de nombres CSS.","Reutilizar el sello de marca con moderación.","Mantener la navegación consistente.","Mantener la terminal como módulo aislado.","Asegurar que las rutas tengan salida.","Conservar una fuente de verdad para proyectos.","Mantener enlaces de repositorios trazables.","No publicar información privada.","Separar contenido de presentación cuando sea posible.","Mantener el selector de idioma preparado para traducciones reales.","Evitar duplicar lógica de estado.","Usar arrays estables para renderizados.","Conservar comentarios de dirección artística.","Mantener reduced-motion junto al componente afectado.","Guardar findings de investigación en documentación.","Definir criterios de aceptación antes de editar.","Revisar cambios contra la identidad superior.","Registrar decisiones rechazadas y motivo.","Preparar rollback mediante checkpoint."],
}

rows = []
number = 1
for family, criteria in families.items():
    for criterion in criteria:
        rows.append(f"| {number:03d} | {family} | {criterion} | Revisar contraste, composición y materialidad. | Revisar comprensión, navegación y carga cognitiva. | Revisar semántica, rendimiento y estados. | Revisar compatibilidad con NOIACORE y con todos los demás criterios. | Aplicar si las cuatro capas son compatibles. |")
        number += 1

header = """# Matriz de 200 criterios de diseño y auditoría cruzada\n\nCada criterio se evalúa en cuatro capas independientes: **visual**, **experiencia**, **técnica** y **coherencia sistémica**. La columna final expresa la regla de decisión: no se aplica una mejora estética si rompe accesibilidad, rendimiento, contenido o la identidad NOIACORE.\n\n| ID | Familia | Criterio | Capa visual | Capa de experiencia | Capa técnica | Capa sistémica | Decisión |\n|---:|---|---|---|---|---|---|---|\n"""
Path("/home/ubuntu/belentani-eu/design-criteria-200.md").write_text(header + "\n".join(rows) + "\n", encoding="utf-8")
print(f"Generated {len(rows)} criteria")
